
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto_1;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tipo_dato = 2;
  public static final int pr_ejecutar = 36;
  public static final int pr_o_si = 18;
  public static final int s_mult = 41;
  public static final int pr_incremento = 24;
  public static final int pr_inicio = 7;
  public static final int pr_como = 12;
  public static final int pr_imprimir = 37;
  public static final int pr_pot = 9;
  public static final int igual = 62;
  public static final int cor_c = 59;
  public static final int identificador = 3;
  public static final int pr_entonces = 15;
  public static final int cor_a = 58;
  public static final int pr_param = 52;
  public static final int pr_hasta = 29;
  public static final int pr_f_segun = 20;
  public static final int s_interrogacion_c = 53;
  public static final int caracter = 5;
  public static final int mayorque = 51;
  public static final int s_interrogacion_a = 49;
  public static final int pr_fin = 8;
  public static final int s_resta = 40;
  public static final int pr_f_funcion = 35;
  public static final int s_asignacion = 47;
  public static final int pr_not = 66;
  public static final int pr_and = 65;
  public static final int s_suma = 39;
  public static final int numero = 6;
  public static final int s_div = 42;
  public static final int pr_mientras = 26;
  public static final int pr_convalor = 13;
  public static final int pr_f_mientras = 27;
  public static final int pr_imprimir_nl = 38;
  public static final int pr_metodo = 32;
  public static final int EOF = 0;
  public static final int pr_si = 14;
  public static final int error = 1;
  public static final int comen_m_linea_a = 56;
  public static final int s_coma = 43;
  public static final int menorigual = 60;
  public static final int pr_repetir = 28;
  public static final int pr_fin_para = 25;
  public static final int pr_para = 23;
  public static final int menorque = 50;
  public static final int s_puntoComa = 46;
  public static final int pr_mod = 10;
  public static final int pr_or = 64;
  public static final int comen_m_linea_ = 57;
  public static final int pr_con = 55;
  public static final int mayorigual = 61;
  public static final int comen_linea = 54;
  public static final int pr_ingresar = 11;
  public static final int diferente = 63;
  public static final int pr_segun = 19;
  public static final int pr_hacer = 21;
  public static final int pr_contrario = 17;
  public static final int pr_f_metodo = 33;
  public static final int pr_funcion = 34;
  public static final int pr_finsi = 16;
  public static final int par_c = 45;
  public static final int pr_retornar = 31;
  public static final int pr_contra_entonces = 22;
  public static final int pr_hastaq = 30;
  public static final int par_a = 44;
  public static final int cadena = 4;
  public static final int boolean_ = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tipo_dato",
  "identificador",
  "cadena",
  "caracter",
  "numero",
  "pr_inicio",
  "pr_fin",
  "pr_pot",
  "pr_mod",
  "pr_ingresar",
  "pr_como",
  "pr_convalor",
  "pr_si",
  "pr_entonces",
  "pr_finsi",
  "pr_contrario",
  "pr_o_si",
  "pr_segun",
  "pr_f_segun",
  "pr_hacer",
  "pr_contra_entonces",
  "pr_para",
  "pr_incremento",
  "pr_fin_para",
  "pr_mientras",
  "pr_f_mientras",
  "pr_repetir",
  "pr_hasta",
  "pr_hastaq",
  "pr_retornar",
  "pr_metodo",
  "pr_f_metodo",
  "pr_funcion",
  "pr_f_funcion",
  "pr_ejecutar",
  "pr_imprimir",
  "pr_imprimir_nl",
  "s_suma",
  "s_resta",
  "s_mult",
  "s_div",
  "s_coma",
  "par_a",
  "par_c",
  "s_puntoComa",
  "s_asignacion",
  "boolean_",
  "s_interrogacion_a",
  "menorque",
  "mayorque",
  "pr_param",
  "s_interrogacion_c",
  "comen_linea",
  "pr_con",
  "comen_m_linea_a",
  "comen_m_linea_",
  "cor_a",
  "cor_c",
  "menorigual",
  "mayorigual",
  "igual",
  "diferente",
  "pr_or",
  "pr_and",
  "pr_not"
  };
}

